package com.soba.sobamod;

import cpw.mods.fml.common.ModMetadata;

public class ModInfo {
	public static void loadInfo(ModMetadata noodlesinfo) {
		noodlesinfo.modId = SobaMod.MODID;
		noodlesinfo.description = "This MOD is very realistic! I think the person who likes soba very much is funny. Many items about soba is added in this MOD.                                The person who cooperated                                                   A cord: Other author of MOD and Modding Wiki  Translation: bamboo1029  Ideas: Many people";
		noodlesinfo.version = SobaMod.VERSION;
		noodlesinfo.url = "http://forum.minecraftuser.jp/viewtopic.php?f=13&t=30735";
		noodlesinfo.authorList.add("88taishi88");
		noodlesinfo.credits = "Many people helped me";
		noodlesinfo.autogenerated = false;
	}

}
